title: El blog de sfraguor
description: Este blog está basado en tema para Jekill Cayman Blog, un tema responsive con características social/SEO.
show_downloads: false
google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
my-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Sergio Fragua"
image: /thumbnail-jumbo.png
twitter:
  username: sfraguor
#  site:
#  admins:
