title: Aprende a ser frontend
description: En este blog podrás aprender todo lo necesario para ser un buen desarrolador frontend.
show_downloads: false
google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
my-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Sergio Fragua"
image: /thumbnail-jumbo.png
twitter:
  username: sfraguor
#  site:
#  admins:
