title: El blog de sfraguor
description: Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and GitHub Pages, with social/SEO features.
show_downloads: false
google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
my-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Sergio Fragua"
image: /thumbnail-jumbo.png
twitter:
  username: sfraguor
#  site:
#  admins:
